// articles-extra.js — Articles ajoutés manuellement à AfriPolitique.
// Chargé APRÈS articles-data.js. Réinjecte des articles que l'automatisation
// de publication pourrait régénérer/supprimer (ex. dossier Sahel).
(function () {
  if (typeof ARTICLES === "undefined") return;
  ARTICLES["sahel-terrorisme-2026"] = {
    cat: "cat-securite", catLabel: "Sahel — Sécurité",
    img: "https://upload.wikimedia.org/wikipedia/commons/2/2d/GARSI-SAHEL_Niger%2C_2019.png",
    title: "Sahel : l'heure des ruptures — quand le djihadisme devient une menace d'État",
    excerpt: "Aéroport de Niamey frappé en plein cœur, ministre malien de la Défense tué près de Bamako, capitale sous blocus, alliance inédite entre djihadistes et rebelles touareg : le Sahel a basculé. Décryptage d'une menace qui ne se contente plus de tuer — elle administre, négocie et lorgne l'État. Et avance vers le golfe de Guinée.",
    author: "Rédaction AfriPolitique", date: "20 juin 2026", read: "16 min",
    body: [
      "Le 18 juin 2026, peu avant l'aube, des assaillants lancés à bord de trois véhicules — dont certains équipés de ceintures explosives — ont frappé l'aéroport international Diori-Hamani et la base aérienne attenante de Niamey. Au cœur de la capitale nigérienne, à quelques centaines de mètres des avions de combat de l'armée et des chancelleries occidentales. Le bilan officiel fait état de onze soldats nigériens et deux civils tués ; vingt-deux assaillants ont été abattus et plus d'une vingtaine capturés vivants. Quelques heures plus tard, le Groupe de soutien à l'islam et aux musulmans (GSIM, plus connu sous son acronyme arabe JNIM), branche sahélienne d'Al-Qaïda, revendiquait l'opération.",
      "Frapper un aéroport international, c'est frapper un symbole. Ce n'est plus la guerre des sables lointains, celle des embuscades sur des pistes que personne ne connaît. C'est la guerre portée au seuil du pouvoir. Et cette attaque n'a rien d'un accident isolé : elle s'inscrit dans une séquence qui, depuis le printemps 2026, a fait vaciller l'ordre sécuritaire de toute une région.",
      "Deux mois plus tôt, le 26 avril 2026, le colonel Sadio Camara, ministre malien de la Défense et figure centrale de la junte de Bamako, était tué à Kati — la ville-garnison qui abrite la principale base militaire du pays et le cœur du régime — par une voiture piégée lançée à l'aube. Il faut ici lever une confusion fréquente : ce n'est pas à Gao que le ministre a trouvé la mort, mais à Kati, aux portes de Bamako, lors de l'offensive la plus coordonnée de toute l'histoire du conflit malien. Ce jour-là, le JNIM et les rebelles touareg du Front de libération de l'Azawad (FLA) ont frappé simultanément Bamako, Kati, Kidal, Gao, Sévaré et Mopti. Le général Assimi Goïta, chef de l'État, a dû être évacué. Et dans le Nord, la ville stratégique de Kidal est tombée.",
      "Niamey, Kati, Kidal, Bamako assiégée par un blocus de carburant : en quelques mois, le Sahel a franchi un seuil. Cet article entend lever l'équivoque sur ce qui se joue réellement — les risques, les points de rupture, et l'évolution accélérée de groupes qui ne se contentent plus de frapper, mais commencent à administrer, à faire le siège des capitales, à négocier d'égal à égal, et à se projeter vers les pays côtiers du golfe de Guinée. Pour comprendre ce basculement, il faut d'abord savoir qui combat qui.",

      "<strong style=\"display:block;font-family:inherit;font-size:1.25rem;margin:1.6rem 0 .3rem;border-left:4px solid #c00;padding-left:10px;line-height:1.3;\">Deux organisations, une même région : qui combat-on vraiment ?</strong>",
      "On parle souvent « des terroristes » au Sahel comme d'un bloc indistinct. C'est une erreur d'analyse aux conséquences stratégiques. Deux organisations rivales structurent l'essentiel de la violence djihadiste, et leurs différences comptent autant que leurs points communs.",
      "<strong style=\"display:block;font-size:1.05rem;margin:1.1rem 0 .2rem;\">Le JNIM : la franchise d'Al-Qaïda, patiente et enracinée</strong>",
      "Le JNIM naît officiellement le 2 mars 2017, de la fusion de quatre organisations : Ansar Dine, la Katiba Macina, Al-Mourabitoune et la branche saharienne d'Al-Qaïda au Maghreb islamique (AQMI). À sa tête, un homme : Iyad Ag Ghali, ancien chef de la rébellion touarège des années 1990 devenu émir djihadiste. Affaibli par l'intervention française de 2013, il a su, en 2017, fédérer des katibas dispersées pour en faire la principale force insurrectionnelle du Sahel central. Le JNIM relève d'Al-Qaïda et en épouse la doctrine : implantation locale patiente, recherche d'un ancrage communautaire, gouvernance graduelle plutôt que terreur spectaculaire. Sa figure intellectuelle, le prédicateur peul Amadou Koufa, dirige la Katiba Macina et incarne l'enracinement du mouvement dans les terroirs du centre du Mali.",
      "<strong style=\"display:block;font-size:1.05rem;margin:1.1rem 0 .2rem;\">L'EIGS : la province de l'État islamique, brutale et frontalière</strong>",
      "Son rival se nomme État islamique dans le Grand Sahara (EIGS), aujourd'hui désigné « Province Sahel » de l'État islamique (ISSP). Né en mai 2015 d'une scission d'Al-Mourabitoune, lorsque Adnane Abou Walid al-Sahraoui prête allégeance à Daech, le groupe a longtemps prospéré dans la zone dite « des trois frontières » — Mali, Niger, Burkina Faso, autour de Ménaka et Tillabéri. Son fondateur a été tué par l'armée française le 17 août 2021 ; lui a succédé Abou al-Bara al-Sahraoui, présenté comme le « wali » de la province sahélienne. L'EIGS pratique une violence plus frontale, des massacres de masse et une logique d'expansion territoriale brutale, sans le souci de « consentement » qui caractérise la stratégie d'Al-Qaïda.",
      "<strong style=\"display:block;font-size:1.05rem;margin:1.1rem 0 .2rem;\">Frères ennemis — sauf quand l'étau se resserre</strong>",
      "Points communs : une matrice salafiste-djihadiste, le rejet de l'État laïc et des frontières héritées de la colonisation, le financement par la zakat imposée, les enlèvements, l'orpaillage et les trafics. Différences décisives : l'allégeance (Al-Qaïda contre l'État islamique), la méthode (enracinement contre conquête), et le rapport aux populations. Surtout, JNIM et EIGS se combattent ouvertement depuis 2019, parfois plus durement qu'ils ne combattent les armées nationales. Mais 2026 a montré une inflexion troublante : confrontés à des pertes de terrain, les deux frères ennemis ont tenté une alliance inédite pour attaquer le Niger — avant d'y être repoussés. Le signal n'en demeure pas moins inquiétant : la rivalité djihadiste, longtemps présentée comme une assurance pour les États, n'est plus une garantie.",

      "<strong style=\"display:block;font-family:inherit;font-size:1.25rem;margin:1.6rem 0 .3rem;border-left:4px solid #c00;padding-left:10px;line-height:1.3;\">De Serval à Barkhane : treize ans d'une guerre qui n'a pas été gagnée</strong>",
      "Pour mesurer le chemin parcouru, il faut revenir à janvier 2013. Les colonnes djihadistes foncent alors sur Bamako. Le 11 janvier, la France déclenche l'opération Serval : l'avancée est stoppée, Tombouctou et Gao sont reprises, et l'intervention est saluée comme un succès militaire. En août 2014, Serval se mue en opération Barkhane, élargie à l'ensemble du Sahel : jusqu'à 5 500 soldats français, un quartier général à N'Djaména, et un allié pivot, le Tchad d'Idriss Déby, dont l'armée fournit certaines des troupes les plus aguerries de la région.",
      "Autour de ce dispositif se construit une architecture régionale : le G5 Sahel — Mauritanie, Mali, Burkina Faso, Niger, Tchad — censé porter une force conjointe antiterroriste, appuyée par la mission onusienne MINUSMA et par les forces spéciales européennes de la task force Takuba. Sur le papier, une coalition. Dans les faits, une machine lourde, sous-financée, minée par les rivalités, et incapable d'enrayer l'extension de la violence du nord vers le centre du Mali, puis vers le Burkina et l'ouest du Niger.",
      "Treize ans plus tard, le constat est sans appel : la pression militaire a éliminé des chefs — al-Sahraoui, plusieurs cadres d'AQMI — mais n'a jamais tari le recrutement ni résolu les causes profondes : déficit d'État, conflits fonciers et communautaires, abandon des périphéries, exactions qui nourrissent le ressentiment. La force a décapité ; elle n'a pas désarmé.",

      "<strong style=\"display:block;font-family:inherit;font-size:1.25rem;margin:1.6rem 0 .3rem;border-left:4px solid #c00;padding-left:10px;line-height:1.3;\">2020-2023 : les putschistes, la Russie et la promesse sécuritaire</strong>",
      "C'est sur l'échec ressenti de cette présence française que prospèrent les coups d'État. Au Mali, Assimi Goïta renverse le pouvoir en août 2020, puis confisque la transition en mai 2021. Au Burkina Faso, deux putschs se succèdent en 2022, portant Ibrahim Traoré au sommet en septembre. Au Niger, le général Abdourahamane Tiani s'empare du pouvoir en juillet 2023. Partout, le même argument : les civils ont échoué à protéger le pays, les militaires feront mieux. La sécurité devient la justification suprême du pouvoir.",
      "Le tournant est aussi géopolitique. Bamako fait venir les paramilitaires russes de Wagner dès décembre 2021 ; six mois plus tard, l'armée française est priée de partir. Le Mali quitte le G5 Sahel le 15 mai 2022 ; le Burkina et le Niger l'enterrent en décembre 2023, signant la « mort cérébrale » de l'organisation. Le 24 septembre 2023, Emmanuel Macron annonce le retrait des derniers soldats français du Niger : fin d'une décennie de présence militaire occidentale. Les trois juntes scellent leur rupture en créant, en septembre 2023, l'Alliance des États du Sahel (AES), avant de claquer la porte de la CEDEAO.",
      "Wagner, devenu Africa Corps après la mort d'Evgueni Prigojine, hérite du contrat sécuritaire. La promesse est limpide : là où la France a échoué, la Russie vaincra. Trois ans plus tard, cette promesse se fracasse sur le réel.",

      "<strong style=\"display:block;font-family:inherit;font-size:1.25rem;margin:1.6rem 0 .3rem;border-left:4px solid #c00;padding-left:10px;line-height:1.3;\">Le bilan : un objectif manqué, des chiffres qui accablent</strong>",
      "La priorité affichée des régimes de l'AES est la sécurité. Qu'en est-il, à l'épreuve des faits et des chiffres ? Le verdict est brutal. Selon le Global Terrorism Index 2026, le Sahel concentre, pour la troisième année consécutive, près de la moitié des décès liés au terrorisme dans le monde : environ 2 700 morts sur les 5 582 recensés au plan mondial en 2025. L'ONG ACLED, qui adopte une méthodologie plus large incluant l'ensemble des violences armées, avance un bilan bien plus lourd : plus de 10 000 morts au Mali, au Burkina Faso et au Niger sur la seule année écoulée.",
      "Derrière les morts, l'effondrement humanitaire. En juin 2025, le Bureau des Nations unies pour la coordination des affaires humanitaires estimait à près de 29 millions le nombre d'habitants ayant besoin d'aide et de protection dans les pays du Sahel. Des millions de déplacés, des milliers d'écoles fermées, des pans entiers de territoire soustraits à l'autorité de l'État.",
      "Les massacres de civils, eux, ont atteint une échelle inédite. Le 24 août 2024, à Barsalogho, dans le nord du Burkina Faso, le JNIM a tué jusqu'à 600 personnes — selon une évaluation française —, pour la plupart des civils réquisitionnés par l'armée pour creuser des tranchées défensives. C'est le massacre le plus meurtrier de l'histoire du pays. Il dit aussi la dérive d'une riposte qui, en militarisant les villageois au sein des Volontaires pour la défense de la patrie (VDP), expose les populations et alimente le cycle des représailles.",
      "Quant au coût économique, il se chiffre désormais en effondrement. Le blocus du carburant imposé au Mali en est l'illustration la plus spectaculaire — et la plus novatrice.",

      "<strong style=\"display:block;font-family:inherit;font-size:1.25rem;margin:1.6rem 0 .3rem;border-left:4px solid #c00;padding-left:10px;line-height:1.3;\">Le blocus de Bamako : la guerre économique comme arme stratégique</strong>",
      "Depuis le début du mois de septembre 2025, le JNIM a cessé de se contenter d'attaquer : il étrangle. En s'en prenant systématiquement aux camions-citernes qui acheminent le carburant depuis le Sénégal et la Côte d'Ivoire — plus d'une centaine de véhicules incendiés, des chauffeurs enlevés —, le groupe a imposé un blocus de fait à un pays enclavé qui dépend entièrement de ses importations par la route.",
      "Dès octobre 2025, la pénurie a gagné Bamako elle-même. Stations-service fermées, files d'attente interminables, coupures d'électricité, écoles fermées, ambassades appelant leurs ressortissants à évacuer : la capitale d'un État souverain s'est retrouvée asphyxiée par une organisation qui ne l'a jamais conquise militairement. C'est une rupture conceptuelle majeure. Le JNIM démontre qu'il peut paralyser un pays sans en prendre les villes, en coupant simplement ses artères vitales. La menace n'est plus seulement létale ; elle est désormais systémique.",

      "<strong style=\"display:block;font-family:inherit;font-size:1.25rem;margin:1.6rem 0 .3rem;border-left:4px solid #c00;padding-left:10px;line-height:1.3;\">Kidal et l'alliance avec les Touareg : le saut qualitatif</strong>",
      "L'autre rupture de 2026 est politique. Pendant des années, les factions rebelles touarègues du Nord malien — réunies aujourd'hui dans le FLA, dirigé depuis 2024 par Alghabass Ag Intalla — ont maintenu une distance de principe avec les djihadistes du JNIM. Coexistence tactique, oui ; alliance assumée, non. L'offensive d'avril 2026 a fait voler en éclats cette ligne de démarcation. En aidant les rebelles à reprendre Kidal — verrou stratégique du Nord qu'ils convoitaient depuis des années —, le JNIM a scellé une convergence sur le champ de bataille. Fait révélateur : quelques jours plus tard, l'Africa Corps russe se retirait de Kidal aux côtés de l'armée malienne, au terme, semble-t-il, d'une négociation avec les Touareg.",
      "Ce rapprochement entre groupes qui « ne s'entendaient pas auparavant » change la donne. Il offre au JNIM une profondeur territoriale, des relais et une légitimité politique. Il brouille la frontière entre rébellion à revendication autonomiste et insurrection djihadiste. Et il pose une question que l'on croyait réservée à d'autres théâtres : ces groupes sont-ils en train de se doter d'une capacité à gouverner ?",

      "<strong style=\"display:block;font-family:inherit;font-size:1.25rem;margin:1.6rem 0 .3rem;border-left:4px solid #c00;padding-left:10px;line-height:1.3;\">Du maquis au proto-État : le « scénario syrien » hante le Sahel</strong>",
      "Dans les vastes zones qu'il contrôle au nord, au centre, à l'ouest et au sud du Mali, comme dans de larges portions du Burkina, le JNIM ne fait pas que régner par la peur. Il administre. Il impose aux habitants des pactes locaux — souvent désignés par le terme « benkan » —, prélève la zakat sur les récoltes et le bétail, rend la justice, tranche les litiges fonciers, applique une charia graduée. Là où l'État a disparu, il offre un ordre. Un ordre brutal, mais prévisible — et c'est précisément ce qui fait sa force.",
      "Les chercheurs ne s'y trompent pas. Le Hudson Institute pose ouvertement la question : « Le Mali est-il le prochain Afghanistan, la prochaine Syrie ou la prochaine Somalie ? » La comparaison avec le Hayat Tahrir al-Sham (HTS) syrien n'est pas fortuite. En décembre 2024, ce mouvement issu de la nébuleuse djihadiste a renversé Bachar al-Assad et pris Damas, avant de se poser en gouvernement et de chercher une reconnaissance internationale. Selon le spécialiste des mouvements djihadistes Wassim Nasr, les responsables du JNIM cherchent, depuis 2025, à obtenir « la même victoire que le HTC en Syrie » : nationaliser leur combat, afficher une gouvernance islamiste « modérée », et dialoguer avec la communauté internationale.",
      "C'est là le véritable point de rupture. Tant qu'un groupe armé se contente de frapper, il reste une menace sécuritaire. Lorsqu'il administre une région, lève l'impôt, rend la justice et négocie des cessez-le-feu, il devient un acteur politique — un proto-État. La capacité du JNIM à gérer administrativement des territoires entiers, et désormais à nouer des alliances avec d'anciens rivaux, le rapproche dangereusement de ce modèle. Le précédent syrien n'est plus une analogie abstraite : c'est l'horizon que les stratèges du mouvement ont, semble-t-il, choisi de viser.",

      "<strong style=\"display:block;font-family:inherit;font-size:1.25rem;margin:1.6rem 0 .3rem;border-left:4px solid #c00;padding-left:10px;line-height:1.3;\">La projection vers le golfe de Guinée : le front qui s'ouvre</strong>",
      "La menace ne reste pas confinée au Sahel. Depuis 2019, elle déborde vers le sud, en direction des États côtiers du golfe de Guinée : nord de la Côte d'Ivoire, du Bénin et du Togo. Le scénario est désormais documenté par l'International Crisis Group, qui en a fait l'objet d'un rapport entier sur « le dilemme de l'expansion au-delà du Sahel ». La méthode du JNIM y est différente : moins de contrôle territorial, davantage de prosélytisme, d'implantation de réseaux logistiques et d'attaques ciblées. Le groupe teste, recrute, prépare des bases de repli, diversifie ses ressources et desserre la pression militaire sur ses bastions sahéliens.",
      "Les chiffres montrent une dégradation rapide. Le Bénin a vu sa situation se détériorer fortement en 2025. Au Togo, depuis janvier 2025, au moins 62 personnes — 54 civils et 8 militaires — ont été tuées dans une quinzaine d'attaques dans la seule région des Savanes, au nord du pays. Le golfe de Guinée, longtemps épargné, est entré dans le viseur. La logique est implacable : la mer et le désert se rejoignent, et la frontière entre Sahel enclavé et façade atlantique n'est plus un pare-feu.",

      "<strong style=\"display:block;font-family:inherit;font-size:1.25rem;margin:1.6rem 0 .3rem;border-left:4px solid #c00;padding-left:10px;line-height:1.3;\">Que faire ? Quelques pistes pour sortir de l'impasse</strong>",
      "Le diagnostic est sombre, mais il ne condamne pas à l'impuissance. Plusieurs voies, complémentaires plutôt que concurrentes, méritent d'être posées sur la table.",
      "<strong style=\"display:block;font-size:1.05rem;margin:1.1rem 0 .2rem;\">1. Sortir du tout-militaire et restaurer l'État là où il a disparu</strong>",
      "Treize ans d'opérations françaises, puis trois ans d'Africa Corps, ont prouvé une chose : aucune force étrangère ne gagne une guerre qui est d'abord une crise de gouvernance. La priorité n'est pas seulement de tuer des combattants, mais de redéployer des services publics, de la justice, de l'école et de l'eau dans les périphéries abandonnées — précisément là où les groupes armés offrent leur propre ordre. Sans retour de l'État, chaque chef éliminé sera remplacé.",
      "<strong style=\"display:block;font-size:1.05rem;margin:1.1rem 0 .2rem;\">2. Une coopération régionale réaliste, du Sahel au littoral</strong>",
      "Le mur dressé entre l'AES et la CEDEAO est un cadeau fait aux djihadistes, qui se jouent des frontières quand les États s'y enferment. La logique voudrait que les pays côtiers — Côte d'Ivoire, Bénin, Togo, Ghana — et les États sahéliens coordonnent renseignement, surveillance des corridors et sécurisation des frontières, par-delà les querelles diplomatiques. Une coopération internationale rénovée, éventuellement sous l'égide des Nations unies et de l'Union africaine, plutôt qu'une nouvelle force d'occupation : un appui en formation, en renseignement et en logistique, au service de stratégies décidées par les Africains eux-mêmes.",
      "<strong style=\"display:block;font-size:1.05rem;margin:1.1rem 0 .2rem;\">3. L'option de la négociation : tabou à briser ?</strong>",
      "C'est la piste la plus controversée — et, à mes yeux, l'une des plus sérieuses. Les dirigeants des trois pays de l'AES refusent publiquement tout dialogue avec les groupes armés, qu'ils qualifient de pure capitulation. Pourtant, sur le terrain, les faits racontent une autre histoire : selon Wassim Nasr, des négociations auraient eu lieu dès décembre 2024, et une trêve aurait même failli être signée fin mars 2026 entre le JNIM et le gouvernement malien — libération de prisonniers contre levée du blocus du carburant. L'Institut Montaigne plaide pour une « stratégie différenciée » : tout le monde n'est pas négociable, mais certains acteurs, certaines katibas locales, certains accords de désescalade le sont. Refuser par principe toute négociation, c'est se priver d'un levier que l'adversaire, lui, manie déjà.",
      "La nuance est capitale. Négocier ne signifie pas capituler, ni légitimer un projet totalitaire. Cela signifie distinguer les irréductibles idéologiques des combattants recrutés par dépit, ouvrir des couloirs de désescalade locale, échanger des trêves contre la réouverture des routes et des écoles. À l'inverse, le « scénario syrien » — laisser un groupe s'imposer par les armes jusqu'à prendre une capitale — est précisément ce qu'une négociation maîtrisée, menée en position de force et adossée à une stratégie politique, permettrait d'éviter.",
      "<strong style=\"display:block;font-size:1.05rem;margin:1.1rem 0 .2rem;\">4. Tarir les ressources et protéger les civils</strong>",
      "Enfin, rien ne se fera sans assécher les financements — orpaillage illégal, zakat imposée, trafics, rançons — et sans rompre avec une logique de riposte qui transforme les villageois en cibles. La protection des civils n'est pas une question morale annexe : c'est le cœur de la contre-insurrection. Chaque massacre de représailles, chaque réquisition meurtrière comme à Barsalogho, fabrique de nouveaux combattants.",

      "<strong style=\"display:block;font-family:inherit;font-size:1.25rem;margin:1.6rem 0 .3rem;border-left:4px solid #c00;padding-left:10px;line-height:1.3;\">Le seuil franchi</strong>",
      "Niamey en juin, Kati et Kidal en avril, Bamako asphyxiée par le carburant tout l'automne : 2026 restera l'année où le djihadisme sahélien a cessé d'être une simple menace sécuritaire pour devenir une menace d'État. Les groupes frappent plus loin, plus fort, plus haut. Ils nouent des alliances qu'on croyait impossibles. Ils administrent, lèvent l'impôt, négocient. Et ils regardent, à l'est, le précédent d'un mouvement djihadiste devenu gouvernement à Damas.",
      "La question n'est plus de savoir si les armées de l'AES, appuyées par la Russie, gagnent la guerre : elles la perdent, et les chiffres le disent. La vraie question est de savoir si la région saura, à temps, changer de logiciel — substituer à la surenchère militaire et souverainiste une stratégie politique, régionale et, oui, parfois négociée. Faute de quoi le Sahel ne sera pas seulement l'épicentre du terrorisme mondial. Il en deviendra le laboratoire d'un nouvel ordre — celui que les États n'auront pas su empêcher."
    ]
  };
})();
